apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.python.appName }}
  name: {{ .Release.Name }}-{{ .Values.python.appName }}
spec:
  type: {{ .Values.python.service.type }}
  ports:
  - name: "{{ .Values.python.appName }}-service"
    port: {{ .Values.python.service.port }}
    targetPort: {{ .Values.python.containerPort }}
    # nodePort: 31001
  selector:
    app: {{ .Values.python.appName }}
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: result-app-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: result 
#   minReplicas: 2   
#   maxReplicas: 10 
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 70 # Scale up if average CPU > 70m 
