apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docker-app-ingress
  annotations:
    # This tells Kubernetes to use the NGINX controller we enabled in Step 1
    kubernetes.io/ingress.class: webapprouting.kubernetes.azure.com
spec:
  rules:
  - host: dockerapp.{{ .Values.ingress.ip }}.nip.io  # Your domain name
    http:
      paths:
      - path: /{{ .Values.appName }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.appName }} 
            port:
              number: {{ .Values.service.port }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "{{ .Values.appName }}-service"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.containerPort }}
    # nodePort: 31001
  selector:
    app: {{ .Values.appName }}
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: result-app-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: result 
#   minReplicas: 2   
#   maxReplicas: 10 
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 70 # Scale up if average CPU > 70m 
