apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    # This tells Kubernetes to use the NGINX controller we enabled in Step 1
    kubernetes.io/ingress.class: webapprouting.kubernetes.azure.com
spec:
  rules:
  - host: vote.{{ .Values.ingress.ip }}.nip.io  # Your domain name
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: python-release-vote
            port:
              number: 8081
  - host: result.{{ .Values.ingress.ip }}.nip.io  # Your domain name
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-release-result
            port:
              number: 8080
