apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Release.Name }}-{{ .Values.appName }}
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}/{{ .Values.appName }}-app:{{ .Values.image.tag }}
        name: {{ .Values.appName }}
    env: 
    # Redis Connection (Source)
        - name: REDIS_HOST
          value: "redis-release-redis"
        - name: REDIS_PORT
          value: "6379"
        
    # Postgres Connection (Destination)
        - name: POSTGRES_HOST
          value: "postgres-release-postgresql"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-release-postgres-secret
              key: password
          
        # resources:
        #   requests:
        #     cpu: "100m"      
        #     memory: "128Mi"
        #   limits:
        #     cpu: "500m"      
        #     memory: "256Mi"
            
        # readinessProbe:
        #   httpGet:
        #     path: /ready
        #     port: 80
        #   initialDelaySeconds: 15  # Wait 5s before checking the first time
        #   periodSeconds: 10       # Check every 10s
          
        # livenessProbe:
        #   httpGet:
        #     path: /live
        #     port: 80
        #   initialDelaySeconds: 15 # Give the app plenty of time to start
        #   periodSeconds: 20
