global:
  image:
    repository: dockerdemoacrname123.azurecr.io
  ingress:
    ip: 98.70.242.152

node:
  appName: result
  containerPort: 80
  replica: 1
  service:
    type: ClusterIP
    port: 8080
  tag: latest

python:
  appName: vote
  containerPort: 80
  replica: 2
  service:
    type: ClusterIP
    port: 8081
  tag: latest
  