image:
  repository: dockerdemoacrname123.azurecr.io
  tag: latest
service:
  type: ClusterIP
  port: 8081
ingress:
  ip: 98.70.242.152
appName: result
containerPort: 80
replica: 1
DATABASE_URL: postgres://postgres:password@postgres-db-postgresql:5432/postgres
