name: Node.js Build and Test

on:
    workflow_dispatch:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./result 

    # strategy:
    #   matrix:
    #     # Build against multiple Node.js versions
    #     node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache-dependency-path: './result/package-lock.json'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run build
      run: npm run build --if-present

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: az acr login --name examplevotingapp123

    - name: Build and Push Docker Image
      run: |
        docker build -t examplevotingapp123.azurecr.io/harsh-app:${{ github.sha }} .
        docker push examplevotingapp123.azurecr.io/harsh-app:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Set AKS Context
      uses: azure/aks-set-context@v3
      with:
        resource-group: example-voting-rg
        cluster-name: example-voting-aks

    - name: Deploy to AKS
      uses: Azure/k8s-deploy@v4
      with:
        action: deploy
        manifests: |
          k8s-harsh/deployment.yaml
        images: |
          examplevotingapp123.azurecr.io/harsh-app:${{ github.sha }}